services:
  - type: web
    name: hieudoan-portal
    runtime: docker
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: "true"
