services:
  - type: web
    name: hieudoan-portal
    runtime: docker
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: ""
      - key: DB_NAME
        value: hieu_ceo_db
